color0 #161311
color1 #ffb4ab
color2 #e6beab
color3 #d7c2b9
color4 #dfc0b2
color5 #e6beab
color6 #d7c2b9
color7 #e9e1de
color8 #968f8d
color9 #ffb4ab
color10 #e6beab
color11 #d7c2b9
color12 #dfc0b2
color13 #e6beab
color14 #d7c2b9
color15 #e9e1de

cursor                #e9e1de
cursor_text_color     #161311
background            #161311
foreground            #e9e1de
selection_foreground  #ccc5c2
selection_background  #4a4644
url_color             #dfc0b2