# Fuentes
font_family      Maple Mono

bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0
disable_ligatures never

# ── Cursor ──────────────────────────────────
cursor_shape          block
cursor_blink_interval 0

# ── Ventana ──────────────────────────────────
background_opacity     0.95
window_padding_width 0

# ── Misc ─────────────────────────────────────
copy_on_select        yes
allow_remote_control  yes
shell_integration     enabled
confirm_os_window_close 0

# Nerd Fonts — forzar ancho de celdas PUA

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

